spring:
  mail:
    host: smtp.qq.com
    username: 271657370@qq.com
    password: #*****  //授权码
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.ssl.enable: true
      mail.display.sendmail: spring-boot-demo