server:
  port: 8001
spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/tqlin/spring-boot-demo.git #因为国内github不稳定，我这里改到了码云仓
          searchPaths: /cloud-config/config-repo/
          force-pull: true